#ifndef ERRORS_H
#define ERRORS_H

typedef enum
{
    OK,
    READ_EDGES_ERROR,
    READ_POINTS_ERROR,
    FILE_ERROR,
    MEMORY_ALLOCATION_ERROR,
    MODEL_ALREADY_LOADED_ERROR,
    MODEL_IS_NOT_LOADED_ERROR,
    ROTATION_AXIS_ERROR,
    NO_EDGE_ERROR,
    INCORRECT_COMMAND,
    INCORRECT_MODEL
} error_t;


#endif // ERRORS_H
